#!/bin/zsh -f

source "${0:a:h}/tmux-hook-lib.zsh"

setopt monitor no_err_exit
exec 2> /dev/null 1>&2

local session_id="$1"
local tmux_pid="$2"
local session_prefix="$tmux_pid.$session_id"
local my_socket="$REG_RUNTIME_DIR/$session_prefix.reg.sock"

# Ideally this would clean up links... TODO
trap '
    if [[ -e "$my_socket" ]]; then
        command-server-terminate "$my_socket"
        rm "$REG_STATE_DIR/$session_prefix.server.pid"
        rm "$REG_STATE_DIR/$session_prefix.server.log"
    fi
    if [[ -n \"\$sleep_pid\" ]]; then
        kill \$sleep_pid &> /dev/null || true
    fi
    exit
' EXIT INT TERM HUP QUIT

while true; do
    sleep 600 &
    wait $!
    if [[ ! -e "$my_socket" ]]; then
        exit
    fi
done
